---
version: '3.9'

volumes:
  mongodb_data:

services:
  flask:
    image: flaskapp:0.1.8-dev
    build: ./
    ports: [5000:5000]
    volumes: [./app:/app]
    environment:
      GUNICORN_CMD_ARGS: --reload
      MONGO_DSN: mongodb://root:rootpassword@mongodb/
      LOG_LEVEL: debug
      LOG_FORMAT: text
      FILTER_PROBES: '0'

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes: [mongodb_data:/data/db]
    logging:
      driver: none
