version: "3.9"

volumes: 
  mongodb_data:

services:
  flask:
    image: flaskapp:1
    build: ./
    ports: [5000:5000]
    environment: 
      MONGO_DSN: mongodb://root:rootpassword@mongodb/
      GUNICORN_CMD_ARGS: "--log-level=DEBUG"
    volumes: ["./logs:/logs"]

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data:/data/db