version: "3.9"

volumes: 
  mongodb_data:

services:
  flask:
    image: flaskapp:1
    build: ./
    ports: [5000:5000]
    volumes: ["./logs:/logs"]
    environment: 
      MONGO_DSN: mongodb://root:rootpassword@mongodb/   # valid rfc connection string
      GUNICORN_CMD_ARGS: "--capture-output"             # see docs for all options
      LOG_LEVEL: error                                  # debug|info|warning|error|critical
      LOG_FORMAT: json                                  # json|text
      FILTER_PROBES: '1'                                # 0|1 - dont log requests to healthcheck endpoints with access logger

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data:/data/db