---
version: '3.9'

volumes:
  prod_data:

services:
  flask:
    image: flaskapp:0.1.8-prod
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        build_date: '2021-04-26'
        version: 0.1.8-prod
    ports: [5000:5000]
    environment:
      MONGO_URI: mongodb://root:rootpassword@mongo/
      LOG_LEVEL: error
      LOG_FORMAT: json
      FILTER_PROBES: '1'

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes: [prod_data:/data/db]
