---
version: '3.9'

volumes:
  test_data:
  pycache:

services:
  testapp:
    image: flaskapp:0.1.8-dev
    build: ./
    volumes: [pycache:/app/.pytest_cache]
    command: python -m pytest -v --failed-first
    environment:
      MONGO_DSN: mongodb://root:rootpassword@testdb/

  testdb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes: [test_data:/data/db]
    logging:
      driver: none
