version: "3.9"

volumes: 
  mongodb_data:

services:
  testapp:
    image: flaskapp:0.1.8-dev
    build: ./
    command: python -m pytest -v
    environment: 
      MONGO_DSN: mongodb://root:rootpassword@testdb/  
      LOG_LEVEL: debug                                  
      LOG_FORMAT: text                                 
      FILTER_PROBES: '0'

  testdb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data:/data/db
    logging:
      driver: "none"